export const MESSAGE_SUCCESS_TRANSACTION = 'MESSAGE_SUCCESS_TRANSACTION'

export const IO_EVENT = {
	SERVER_CONNECTION: 'connection',
	SERVER_DECONNECTION: 'disconnect',
	CLIENT_CONNECTION: 'connect',
	CLIENT_EMIT_ONSYNC: 'CLIENT_EMIT_ONSYNC',
	CLIENT_EMIT_LOG: 'CLIENT_EMIT_LOG',
}

export const IO_MESSAGE = {
	NEW_USER: 'NEW_USER',
}
